sitter/network/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import Feed, VoteView

app_name = 'network'

urlpatterns = [
    path('', csrf_exempt(Feed.as_view()), name='feed'),
    path('vote/<int:pk>', csrf_exempt(VoteView), name='votes'),
]

sitter/sitter/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('dj-rest-auth/', include('dj_rest_auth.urls')),
    # path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('', include('users.urls')),
    path('network/', include('network.urls', namespace='posts')),
]

sitter/users/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.views.generic import TemplateView
from .views import UserLoginView, RegisterView
admin.autodiscover()

urlpatterns = [
    re_path(r'user_login/$', UserLoginView.as_view(), name='user_login'),
    re_path(r'user_signup/$', RegisterView.as_view(), name='user_signup'),
    re_path(r'signup/$', TemplateView.as_view(template_name="signup.html"), name='signup'),
    re_path(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    re_path(r'^login/', TemplateView.as_view(template_name="login.html"), name='login'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^dj-rest-auth/', include('dj_rest_auth.urls')),
    re_path(r'^dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]

sitter/network/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

User = settings.AUTH_USER_MODEL


class Post(models.Model):
    text = models.TextField(max_length=512)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='author')

    def __str__(self):
        return str(self.text)


class VoteManager(models.Manager):

    def get_likes(self):
        return self.get_queryset().filter(vote__gt=0)

    def get_dislikes(self):
        return self.get_queryset().filter(vote__lt=0)

    def test(self, *args, **kwargs):
        return self.get_queryset().filter(**kwargs)


class Vote(models.Model):
    LIKE = 1
    DISLIKE = -1
    VOTES = [
        (LIKE, 'like'),
        (DISLIKE, 'dislike')
    ]
    vote = models.SmallIntegerField(choices=VOTES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post')

    objects = VoteManager()

sitter/users/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractUser, BaseUserManager
)

GENDERS = [
    ('male', 'male'),
    ('female', 'female'),
]


class CustomUserManager(BaseUserManager):

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Valid email must be set.")
        email = self.normalize_email(email)
        user = self.model(email=email)
        user.username = username
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email,
            username,
            password=password,
        )
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


class User(AbstractUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=256,
        unique=True
    )
    username = models.CharField(max_length=64)
    gender = models.CharField(max_length=8, choices=GENDERS)

    name = models.CharField(max_length=256, blank=True, null=True)
    legal = models.CharField(max_length=256, blank=True, null=True)
    founded = models.CharField(max_length=256, blank=True, null=True)
    type = models.CharField(max_length=256, blank=True, null=True)
    employees = models.CharField(max_length=256, blank=True, null=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    parent_domain = models.CharField(max_length=256, blank=True, null=True)
    ultimate_parent_domain = models.CharField(max_length=256, blank=True, null=True)
    tags = models.CharField(max_length=256, blank=True, null=True)
    industry = models.CharField(max_length=256, blank=True, null=True)
    sector = models.CharField(max_length=256, blank=True, null=True)
    sic_code = models.CharField(max_length=256, blank=True, null=True)
    naics_code = models.CharField(max_length=256, blank=True, null=True)
    technologies = models.CharField(max_length=256, blank=True, null=True)
    technology_categories = models.CharField(max_length=256, blank=True, null=True)
    alexa_global_rank = models.CharField(max_length=256, blank=True, null=True)
    crunchbase = models.CharField(max_length=256, blank=True, null=True)
    twitter = models.CharField(max_length=256, blank=True, null=True)
    facebook = models.CharField(max_length=256, blank=True, null=True)
    linkedin = models.CharField(max_length=256, blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    is_superuser = models.BooleanField(default=False)

sitter/network/forms.py
from django import forms
from .models import Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.urls import reverse


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('Submit', 'submit'))

    text = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': 1,
                'placeholder': 'share something',
            }
        )
    )

    class Meta:
        model = Post
        fields = ['text']

sitter/network/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Vote
from .forms import PostForm
from rest_framework import permissions


class Feed(View):
    permission_classes = [permissions.IsAuthenticated]
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-date')
        form = PostForm()
        votes = Vote.objects.all()
        print(kwargs)
        context = {
            'form': form,
            'feed': posts,
            'votes': votes,
        }
        return render(request, 'network/feed.html', context)

    def post(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-date')
        votes = Vote.objects.all()
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
        context = {
            'form': form,
            'feed': posts,
            'votes': votes,
        }
        return render(request, 'network/feed.html', context)


def VoteView(request, pk):
    post_id = request.POST.get('post_id')
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    vote = int(request.POST.get('vote'))
    kwargs = dict(
        post=post,
        vote=vote,
        user=user,
    )
    unlike = Vote.objects.filter(**kwargs)

    if unlike.exists():
        unlike.delete()
    else:
        Vote.objects.create(**kwargs)

    return redirect('network:feed')

sitter/users/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from rest_framework.decorators import action
from .serializers import UserLoginSerializer, UserRegisterSerializer
from dj_rest_auth.views import LoginView
from dj_rest_auth.registration.views import RegisterView
import time

class UserLoginView(LoginView):
    serializer_class = UserLoginSerializer


class UserRegisterView(RegisterView):
    serializer_class = UserRegisterSerializer

sitter/network/templates/network/feed.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div>
        <div>
            <div><h3>What is on your mind?</h3></div>
            <div>
                {% crispy form %}
            </div>
             {% for post  in feed %}
        </div>
        <div class="card">
            <div class="card-body">
                <div>
                    <div class="card title">
                        <div><span><strong>{{post.author}}</strong></span> <span>{{post.date}}</span></div>
                    </div>
                </div>
                <div class="card-text"><span>{{post.text}}</span></div>
                <div>

                </div>

                <form action="{% url 'network:votes' post.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{ post.id }}">
                    <button name="vote" value="1" class="btn btn-success" type="submit">like</button>
                    <button name="vote" value="-1" class="btn btn-danger" type="submit">dislike</button>
                </form>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

sitter/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sitter">
    <meta name="author" content="Yevhen Bilyk">

    <title>Sitter Social Network</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3dfad9fc97.js" crossorigin="anonymous"></script>
  </head>

<body role="document">

    <nav class="navbar navbar-dark bg-dark">
        <div class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                API endpoints
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                 <a class="dropdown-item" href="{% url 'signup' %}">Signup</a>
                 <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            </div>
        </div>
    </nav>


    <div class="container theme-showcase" role="main">
      {% block content %}{% endblock %}
    </div>
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript">
      var error_response = function(data){
        $('.api-response').html("API Response: " + data.status + ' ' + data.statusText + '<br/>Content: ' + data.responseText);
      }
      var susccess_response = function(data){
        $('.api-response').html("API Response: OK<br/>Content: " + JSON.stringify(data));
      }

      $().ready(function(){
        $('form.ajax-post button[type=submit]').click(function(){
          var form = $('form.ajax-post');
          $.post(form.attr('action'), form.serialize())
          .fail(function(data){error_response(data);})
          .done(function(data){susccess_response(data);});
          return false;
        });
      });
    </script>
    {% block script %}{% endblock %}
  </body>
</html>

sitter/templates/fragments/login_form.html
<!-- Signup form -->
<form class="form-horizontal ajax-post" role="form" action="{% url 'rest_login' %}">{% csrf_token %}
  <div class="form-group">
    <label for="username" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input name="username" type="text" class="form-control" id="username" placeholder="Username">
    </div>
  </div>

  <div class="form-group">
    <label for="password" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input name="password" type="password" class="form-control" id="password" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Login</button>
    </div>
  </div>

  <div class="form-group api-response"></div>
</form>

sitter/templates/fragments/signup_form.html
<!-- Signup form -->
<form class="form-horizontal ajax-post" id="signup" role="form" action="{% url 'rest_register' %}">{% csrf_token %}
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input name="email" type="text" class="form-control" id="email" placeholder="Email">
    </div>
  </div>

  <div class="form-group">
    <label for="username" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input name="username" type="text" class="form-control" id="username" placeholder="Username">
    </div>
  </div>

  <div class="form-group">
    <label for="gender" class="col-sm-2 control-label">Gender</label>
    <div class="col-sm-10">
       <select class="form-control" name="gender">
        <option value="male">male</option>
        <option value="female">female</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="password1" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input name="password1" type="password" class="form-control" id="password1" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <label for="password2" class="col-sm-2 control-label">Repeat password</label>
    <div class="col-sm-10">
      <input name="password2" type="password" class="form-control" id="password2" placeholder="Repeat password">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign up</button>
    </div>
  </div>

  <div class="form-group api-response"></div>
</form>

sitter/templates/home.html
{% extends "base.html" %}

{% block content %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Social Network Demo</h1>
    <p>Welcome Sitter project!</p>
  </div>
{% endblock %}

sitter/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Login</h3><hr/>
    {% include "fragments/login_form.html" %}
  </div>
{% endblock %}

sitter/templates/signup.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <h3>Signup</h3><hr/>
    {% include "fragments/signup_form.html" %}
  </div>
{% endblock %}